services:
  - type: web
    name: breast-cancer-prediction
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -b 0.0.0.0:$PORT"
    autoDeploy: false
    envVars:
      - key: MODEL_PATH
        value: model.h5
